title: "bläGä-blən"
author: "Sevastromo"
description: "A PC game enthusiast's thoughts, experiences, and opnions on whatever they're playing at the moment." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
twitter_username: "sevastromo"
github_username: "sevastromo"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
#rss: rss

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
  
minima:  
  skin: solarized

show_excerpts: true

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
google_analytics: G-45R5LED7EQ

titles_from_headings:
  strip_title: true
  collections: true
  
header_pages:
  - about.md
  - top10.md
  - ratingscale.md
  - archive.md

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
